container:
  image: ruby:latest

task:
  name: RSpec
  bundle_cache:
    folder: /usr/local/bundle
    fingerprint_script:
      - echo $RUBY_VERSION
      - cat Gemfile.lock
    populate_script: make prepare
  script: make test
